dataset:
  description: Blender_Dataset
  path: '../NeRF-Factory/data/blender'
  scene_name: 'chair'
  batch: 10 #batch size
  num_workers: 16 #numworkers

model:
  task: Pose Estimation
  type: 'Encoder & Decoder'
  Encoder_parameters:
    num_conv_blocks: 3
    num_att_blocks: 5
    pos_start_octave: 0
    image_size: 800 # size of input images ( Ex. Synthetic : 800 x 800 )
    pose_embedding: False # Additional Embedding of image poses. True in SRT False in RUST.
  Decoder_parameters:
    num_conv_blocks: 4
    num_att_blocks: 3

train:
  description: PoseNet
  id: Synthetic Dataset
  Epoch: 4000000
  Learning_Rate: 1e-4

wandb:
  project: Training Pose Network with NeRF Synthetic Dataset_onS
  entity: jwjung